GET http://localhost:3000/users

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "elia",
    "password": "merlin"
}

###
GET http://localhost:3000/documents

###

GET http://localhost:3000/documents/4

###

POST http://localhost:3000/documents/add
Content-Type: application/json

{
    "title": "Test",
    "summary": "As the politics and rivalries of the seven human nations waxed and waned, the line of Guardians kept its constant vigil against chaos.",
    "author": "Emilia",
    "textContent": "There were many Guardians over the years, but only one ever held the magical powers of Tirisfal at any given time."
}

###

POST http://localhost:3000/documents/edit/3
Content-Type: application/json

{
    "title": "Ipsum",
    "summary": "Curabitur venenatis commodo mi eget tristique.",
    "author": "Emilia",
    "textContent": "Curabitur venenatis commodo mi eget tristique."
}